package com.bzu.fitnessapp;

import java.util.ArrayList;
import java.util.List;

public class WorkoutMockupDA {

    public List<Workout> getWorkouts() {
        List<Workout> workouts = new ArrayList<>();

        //Cardio Workouts
        workouts.add(new Workout("Running", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Cycling", "Cardio", 45, 400, "Medium", ""));
        workouts.add(new Workout("Jump Rope", "Cardio", 15, 200, "Hard", ""));
        workouts.add(new Workout("Swimming", "Cardio", 60, 500, "Hard", ""));
        workouts.add(new Workout("Brisk Walking", "Cardio", 30, 200, "Easy", ""));
        workouts.add(new Workout("Hiking", "Cardio", 120, 600, "Medium", ""));
        workouts.add(new Workout("Rowing", "Cardio", 30, 250, "Medium", ""));
        workouts.add(new Workout("Stair Climbing", "Cardio", 20, 300, "Hard", ""));
        workouts.add(new Workout("High-Intensity Interval Training", "Cardio", 25, 400, "Hard", ""));
        workouts.add(new Workout("Kickboxing", "Cardio", 40, 500, "Hard", ""));
        workouts.add(new Workout("Dancing", "Cardio", 30, 200, "Medium", ""));
        workouts.add(new Workout("Zumba", "Cardio", 45, 350, "Medium", ""));
        workouts.add(new Workout("Elliptical Machine", "Cardio", 30, 250, "Medium", ""));
        workouts.add(new Workout("Jumping Jacks", "Cardio", 15, 150, "Easy", ""));
        workouts.add(new Workout("Battle Ropes", "Cardio", 20, 300, "Hard", ""));
        workouts.add(new Workout("Box Jumps", "Cardio", 20, 250, "Hard", ""));
        workouts.add(new Workout("Agility Ladder Drills", "Cardio", 30, 200, "Medium", ""));
        workouts.add(new Workout("Sprints", "Cardio", 10, 150, "Hard", ""));
        workouts.add(new Workout("Rollerblading", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Cross-Country Skiing", "Cardio", 60, 500, "Hard", ""));
        workouts.add(new Workout("Step Aerobics", "Cardio", 30, 250, "Medium", ""));
        workouts.add(new Workout("Tabata Training", "Cardio", 20, 300, "Hard", ""));
        workouts.add(new Workout("Burpees", "Cardio", 15, 200, "Hard", ""));
        workouts.add(new Workout("Bear Crawls", "Cardio", 15, 180, "Hard", ""));
        workouts.add(new Workout("Mountain Climbers", "Cardio", 15, 220, "Medium", ""));
        workouts.add(new Workout("Power Walking", "Cardio", 30, 200, "Easy", ""));
        workouts.add(new Workout("Martial Arts", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Soccer", "Cardio", 90, 600, "Medium", ""));
        workouts.add(new Workout("Basketball", "Cardio", 60, 500, "Medium", ""));
        workouts.add(new Workout("Tennis", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Ultimate Frisbee", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Swimming Laps", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Jumping Squats", "Cardio", 20, 250, "Hard", ""));
        workouts.add(new Workout("Skipping", "Cardio", 15, 200, "Medium", ""));
        workouts.add(new Workout("Shadow Boxing", "Cardio", 20, 300, "Medium", ""));
        workouts.add(new Workout("Aqua Aerobics", "Cardio", 30, 200, "Easy", ""));
        workouts.add(new Workout("Dance Cardio", "Cardio", 40, 350, "Medium", ""));
        workouts.add(new Workout("Running Stairs", "Cardio", 20, 250, "Hard", ""));
        workouts.add(new Workout("Agility Cone Drills", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Resistance Band Cardio", "Cardio", 30, 200, "Easy", ""));
        workouts.add(new Workout("Lateral Shuffles", "Cardio", 15, 180, "Medium", ""));
        workouts.add(new Workout("Run/Walk Intervals", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Interval Sprints", "Cardio", 20, 250, "Hard", ""));
        workouts.add(new Workout("Hiking", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Rowing", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Elliptical Trainer", "Cardio", 30, 350, "Medium", ""));
        workouts.add(new Workout("Dancing", "Cardio", 45, 250, "Easy", ""));
        workouts.add(new Workout("Jumping Jacks", "Cardio", 15, 120, "Medium", ""));
        workouts.add(new Workout("High Knees", "Cardio", 10, 100, "Hard", ""));
        workouts.add(new Workout("Burpees", "Cardio", 15, 200, "Hard", ""));
        workouts.add(new Workout("Shadow Boxing", "Cardio", 30, 250, "Medium", ""));
        workouts.add(new Workout("Sprints", "Cardio", 20, 300, "Hard", ""));
        workouts.add(new Workout("Stair Climbing", "Cardio", 20, 250, "Medium", ""));
        workouts.add(new Workout("Kickboxing", "Cardio", 30, 350, "Hard", ""));
        workouts.add(new Workout("Boxing", "Cardio", 30, 300, "Hard", ""));
        workouts.add(new Workout("Aerobics", "Cardio", 45, 300, "Medium", ""));
        workouts.add(new Workout("Zumba", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("CrossFit", "Cardio", 30, 350, "Hard", ""));
        workouts.add(new Workout("Hula Hooping", "Cardio", 30, 200, "Easy", ""));
        workouts.add(new Workout("Skating", "Cardio", 45, 350, "Medium", ""));
        workouts.add(new Workout("Surfing", "Cardio", 60, 500, "Hard", ""));
        workouts.add(new Workout("Biking", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Parkour", "Cardio", 30, 300, "Hard", ""));
        workouts.add(new Workout("Jumping Rope", "Cardio", 20, 200, "Hard", ""));
        workouts.add(new Workout("Rugby", "Cardio", 60, 600, "Hard", ""));
        workouts.add(new Workout("Squash", "Cardio", 60, 500, "Hard", ""));
        workouts.add(new Workout("Tennis", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Badminton", "Cardio", 45, 350, "Medium", ""));
        workouts.add(new Workout("Football", "Cardio", 60, 600, "Hard", ""));
        workouts.add(new Workout("Ultimate Frisbee", "Cardio", 60, 500, "Hard", ""));
        workouts.add(new Workout("Mountain Biking", "Cardio", 60, 400, "Medium", ""));
        workouts.add(new Workout("Jogging", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Step Aerobics", "Cardio", 30, 250, "Medium", ""));
        workouts.add(new Workout("Battle Ropes", "Cardio", 20, 300, "Hard", ""));
        workouts.add(new Workout("Agility Ladder Drills", "Cardio", 15, 150, "Hard", ""));
        workouts.add(new Workout("Skiing", "Cardio", 60, 500, "Hard", ""));
        workouts.add(new Workout("Walking on Treadmill", "Cardio", 30, 250, "Easy", ""));
        workouts.add(new Workout("Jump Squats", "Cardio", 15, 200, "Hard", ""));
        workouts.add(new Workout("Walking Lunges", "Cardio", 15, 150, "Medium", ""));
        workouts.add(new Workout("Treadmill Intervals", "Cardio", 30, 350, "Hard", ""));
        workouts.add(new Workout("Kettlebell Swings", "Cardio", 20, 200, "Medium", ""));
        workouts.add(new Workout("Plyometric Box Jumps", "Cardio", 15, 180, "Hard", ""));
        workouts.add(new Workout("Rowing Machine Intervals", "Cardio", 30, 350, "Hard", ""));
        workouts.add(new Workout("Aerobic Step", "Cardio", 30, 300, "Medium", ""));
        workouts.add(new Workout("Cross Trainer", "Cardio", 30, 350, "Medium", ""));
        workouts.add(new Workout("Pogo Jumps", "Cardio", 10, 100, "Hard", ""));
        workouts.add(new Workout("Power Walking", "Cardio", 30, 200, "Medium", ""));
        workouts.add(new Workout("Sledgehammer Slams", "Cardio", 15, 200, "Hard", ""));



        //Gym Workouts with targeted muscles
        workouts.add(new Workout("Bench Press", "Gym", 30, 250, "Hard", "Chest"));
        workouts.add(new Workout("Squats", "Gym", 40, 300, "Medium", "Legs"));
        workouts.add(new Workout("Deadlift", "Gym", 30, 350, "Hard", "Back, Legs"));
        workouts.add(new Workout("Bicep Curls", "Gym", 20, 150, "Easy", "Arms"));
        workouts.add(new Workout("Leg Press", "Gym", 30, 200, "Medium", "Legs"));
        workouts.add(new Workout("Shoulder Press", "Gym", 25, 220, "Medium", "Shoulders"));
        workouts.add(new Workout("Pull-Ups", "Gym", 15, 180, "Hard", "Back, Biceps"));
        workouts.add(new Workout("Tricep Dips", "Gym", 20, 160, "Medium", "Triceps"));
        workouts.add(new Workout("Chest Fly", "Gym", 25, 180, "Medium", "Chest"));
        workouts.add(new Workout("Lateral Raises", "Gym", 20, 150, "Medium", "Shoulders"));
        workouts.add(new Workout("Leg Extensions", "Gym", 20, 120, "Medium", "Legs"));
        workouts.add(new Workout("Hamstring Curls", "Gym", 20, 120, "Medium", "Legs"));
        workouts.add(new Workout("Cable Tricep Pushdowns", "Gym", 15, 100, "Medium", "Triceps"));
        workouts.add(new Workout("Dumbbell Rows", "Gym", 30, 220, "Medium", "Back"));
        workouts.add(new Workout("Incline Dumbbell Press", "Gym", 30, 240, "Hard", "Chest"));
        workouts.add(new Workout("Machine Chest Press", "Gym", 30, 200, "Medium", "Chest"));
        workouts.add(new Workout("Barbell Rows", "Gym", 30, 250, "Hard", "Back"));
        workouts.add(new Workout("Front Squats", "Gym", 30, 250, "Hard", "Legs"));
        workouts.add(new Workout("Cable Crossovers", "Gym", 20, 150, "Medium", "Chest"));
        workouts.add(new Workout("Kettlebell Swings", "Gym", 20, 180, "Hard", "Legs, Core"));
        workouts.add(new Workout("Barbell Squats", "Gym", 30, 300, "Hard", "Legs"));
        workouts.add(new Workout("Glute Bridges", "Gym", 20, 150, "Medium", "Glutes"));
        workouts.add(new Workout("Plank", "Gym", 5, 50, "Medium", "Core"));
        workouts.add(new Workout("Dumbbell Shoulder Press", "Gym", 25, 220, "Medium", "Shoulders"));
        workouts.add(new Workout("Leg Raises", "Gym", 15, 80, "Easy", "Core"));
        workouts.add(new Workout("Mountain Climbers", "Gym", 15, 200, "Hard", "Core"));
        workouts.add(new Workout("Leg Press Machine", "Gym", 30, 200, "Medium", "Legs"));
        workouts.add(new Workout("Cable Lateral Raises", "Gym", 20, 120, "Medium", "Shoulders"));
        workouts.add(new Workout("Seated Row Machine", "Gym", 30, 180, "Medium", "Back"));
        workouts.add(new Workout("Machine Leg Press", "Gym", 30, 220, "Medium", "Legs"));
        workouts.add(new Workout("Dumbbell Bench Press", "Gym", 30, 240, "Hard", "Chest"));
        workouts.add(new Workout("Chest Press Machine", "Gym", 30, 200, "Medium", "Chest"));
        workouts.add(new Workout("Tricep Kickbacks", "Gym", 20, 100, "Easy", "Triceps"));
        workouts.add(new Workout("Dumbbell Flyes", "Gym", 20, 150, "Medium", "Chest"));
        workouts.add(new Workout("Kettlebell Deadlifts", "Gym", 30, 220, "Medium", "Legs"));
        workouts.add(new Workout("Barbell Shrugs", "Gym", 25, 200, "Medium", "Traps"));
        workouts.add(new Workout("Cable Rows", "Gym", 30, 180, "Medium", "Back"));
        workouts.add(new Workout("Pec Deck Machine", "Gym", 30, 200, "Medium", "Chest"));
        workouts.add(new Workout("Smith Machine Squats", "Gym", 30, 250, "Hard", "Legs"));
        workouts.add(new Workout("Seated Dumbbell Shoulder Press", "Gym", 25, 220, "Medium", "Shoulders"));
        workouts.add(new Workout("Hammer Curls", "Gym", 20, 150, "Medium", "Arms"));
        workouts.add(new Workout("Skull Crushers", "Gym", 20, 140, "Medium", "Triceps"));
        workouts.add(new Workout("Chest Press with Dumbbells", "Gym", 30, 240, "Hard", "Chest"));
        workouts.add(new Workout("Lying Leg Press", "Gym", 30, 250, "Hard", "Legs"));
        workouts.add(new Workout("Cable Tricep Extensions", "Gym", 20, 130, "Medium", "Triceps"));
        workouts.add(new Workout("Plate Loaded Leg Press", "Gym", 30, 300, "Hard", "Legs"));
        workouts.add(new Workout("Single Arm Dumbbell Row", "Gym", 25, 180, "Medium", "Back"));
        workouts.add(new Workout("Dumbbell Lateral Raise", "Gym", 20, 140, "Medium", "Shoulders"));
        workouts.add(new Workout("Standing Calf Raises", "Gym", 25, 150, "Medium", "Calves"));
        workouts.add(new Workout("Leg Curls", "Gym", 20, 100, "Medium", "Legs"));
        workouts.add(new Workout("Dumbbell Step Ups", "Gym", 30, 200, "Medium", "Legs"));
        workouts.add(new Workout("Decline Bench Press", "Gym", 30, 240, "Hard", "Chest"));
        workouts.add(new Workout("Incline Dumbbell Flyes", "Gym", 25, 180, "Medium", "Chest"));
        workouts.add(new Workout("Overhead Dumbbell Tricep Extension", "Gym", 20, 130, "Medium", "Triceps"));
        workouts.add(new Workout("Cable Face Pulls", "Gym", 20, 120, "Medium", "Shoulders"));
        workouts.add(new Workout("Reverse Flyes", "Gym", 20, 130, "Medium", "Shoulders"));
        workouts.add(new Workout("Goblet Squats", "Gym", 30, 200, "Medium", "Legs"));
        workouts.add(new Workout("Kettlebell Swings", "Gym", 20, 180, "Hard", "Legs, Core"));
        workouts.add(new Workout("Plank Rows", "Gym", 15, 150, "Hard", "Core, Back"));
        workouts.add(new Workout("Medicine Ball Slams", "Gym", 15, 200, "Hard", "Full Body"));
        workouts.add(new Workout("Cable Woodchoppers", "Gym", 20, 150, "Medium", "Core"));
        workouts.add(new Workout("Sled Pushes", "Gym", 30, 300, "Hard", "Legs, Full Body"));
        workouts.add(new Workout("Dumbbell Chest Press", "Gym", 30, 240, "Hard", "Chest"));
        workouts.add(new Workout("Glute Kickbacks", "Gym", 20, 150, "Medium", "Glutes"));
        workouts.add(new Workout("Reverse Crunches", "Gym", 15, 100, "Easy", "Core"));
        workouts.add(new Workout("Seated Dumbbell Flyes", "Gym", 20, 140, "Medium", "Chest"));
        workouts.add(new Workout("Inverted Rows", "Gym", 20, 180, "Medium", "Back"));
        workouts.add(new Workout("Russian Twists", "Gym", 15, 100, "Medium", "Core"));
        workouts.add(new Workout("Leg Raises", "Gym", 15, 80, "Easy", "Core"));
        workouts.add(new Workout("Dumbbell Shrugs", "Gym", 25, 200, "Medium", "Traps"));
        workouts.add(new Workout("Cable Upright Rows", "Gym", 20, 130, "Medium", "Shoulders"));
        workouts.add(new Workout("Standing Barbell Press", "Gym", 25, 220, "Hard", "Shoulders"));
        workouts.add(new Workout("Chest Supported Rows", "Gym", 30, 180, "Medium", "Back"));
        workouts.add(new Workout("Hip Thrusts", "Gym", 30, 250, "Hard", "Glutes"));
        workouts.add(new Workout("Dumbbell Sumo Squats", "Gym", 30, 220, "Medium", "Legs"));
        workouts.add(new Workout("Cable Kickbacks", "Gym", 20, 130, "Medium", "Glutes"));
        workouts.add(new Workout("Medicine Ball Twists", "Gym", 15, 120, "Medium", "Core"));
        workouts.add(new Workout("Box Squats", "Gym", 30, 250, "Hard", "Legs"));
        workouts.add(new Workout("T-Bar Row", "Gym", 30, 250, "Hard", "Back"));
        workouts.add(new Workout("Dumbbell Front Raise", "Gym", 20, 140, "Medium", "Shoulders"));
        workouts.add(new Workout("Barbell Curl", "Gym", 20, 150, "Medium", "Arms"));
        workouts.add(new Workout("Lying Leg Raises", "Gym", 15, 100, "Easy", "Core"));
        workouts.add(new Workout("Dumbbell Side Bend", "Gym", 20, 130, "Medium", "Core"));
        workouts.add(new Workout("Plank Jacks", "Gym", 15, 150, "Medium", "Core"));
        workouts.add(new Workout("Stability Ball Pass", "Gym", 15, 150, "Medium", "Core"));


        return workouts;
    }
}
